import type { Metadata } from "next";
import { Inika, Source_Sans_3, Inter } from "next/font/google";
import "../globals.css";
import { ReactNode } from "react";
import { getMessages } from "next-intl/server";
import IntlProviderCustom from "@/src/components/nextIntl/IntlProvider";
import { StoreProvider } from "@/src/state/StoreProvider";

const inika = Inika({
  weight: ["400", "700"],
  variable: "--font-inika",
  subsets: ["latin"],
});
const sourceSans = Source_Sans_3({
  variable: "--font-source-sans-3",
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
  params,
}: {
  children: ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  const messages = await getMessages();
  return (
    <html
      lang={locale}
      className={`${inika.variable} ${sourceSans.variable} text-primary h-full antialiased`}
    >
      <body className="size-full flex flex-col mx-auto">
        <IntlProviderCustom locale={locale} messages={messages}>
          <StoreProvider>{children}</StoreProvider>
        </IntlProviderCustom>
      </body>
    </html>
  );
}
